{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "22dc6618",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-04-26 20:13:24.492 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\tomcz\\Documents\\Python\\lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from pathlib import Path\n",
    "\n",
    "import streamlit as st\n",
    "from PIL import Image\n",
    "\n",
    "\n",
    "# --- PATH SETTINGS ---\n",
    "current_dir = Path(__file__).parent if \"__file__\" in locals() else Path.cwd()\n",
    "css_file = current_dir / \"styles\" / \"main.css\"\n",
    "resume_file = current_dir / \"assets\" / \"CV.pdf\"\n",
    "profile_pic = current_dir / \"assets\" / \"profile-pic.png\"\n",
    "\n",
    "\n",
    "# --- GENERAL SETTINGS ---\n",
    "PAGE_TITLE = \"Digital CV | John Doe\"\n",
    "PAGE_ICON = \":wave:\"\n",
    "NAME = \"John Doe\"\n",
    "DESCRIPTION = \"\"\"\n",
    "Senior Data Analyst, assisting enterprises by supporting data-driven decision-making.\n",
    "\"\"\"\n",
    "EMAIL = \"johndoe@email.com\"\n",
    "SOCIAL_MEDIA = {\n",
    "    \"YouTube\": \"https://youtube.com/c/codingisfun\",\n",
    "    \"LinkedIn\": \"https://linkedin.com\",\n",
    "    \"GitHub\": \"https://github.com\",\n",
    "    \"Twitter\": \"https://twitter.com\",\n",
    "}\n",
    "PROJECTS = {\n",
    "    \"🏆 Sales Dashboard - Comparing sales across three stores\": \"https://youtu.be/Sb0A9i6d320\",\n",
    "    \"🏆 Income and Expense Tracker - Web app with NoSQL database\": \"https://youtu.be/3egaMfE9388\",\n",
    "    \"🏆 Desktop Application - Excel2CSV converter with user settings & menubar\": \"https://youtu.be/LzCfNanQ_9c\",\n",
    "    \"🏆 MyToolBelt - Custom MS Excel add-in to combine Python & Excel\": \"https://pythonandvba.com/mytoolbelt/\",\n",
    "}\n",
    "\n",
    "\n",
    "st.set_page_config(page_title=PAGE_TITLE, page_icon=PAGE_ICON)\n",
    "\n",
    "\n",
    "# --- LOAD CSS, PDF & PROFIL PIC ---\n",
    "with open(css_file) as f:\n",
    "    st.markdown(\"<style>{}</style>\".format(f.read()), unsafe_allow_html=True)\n",
    "with open(resume_file, \"rb\") as pdf_file:\n",
    "    PDFbyte = pdf_file.read()\n",
    "profile_pic = Image.open(profile_pic)\n",
    "\n",
    "\n",
    "# --- HERO SECTION ---\n",
    "col1, col2 = st.columns(2, gap=\"small\")\n",
    "with col1:\n",
    "    st.image(profile_pic, width=230)\n",
    "\n",
    "with col2:\n",
    "    st.title(NAME)\n",
    "    st.write(DESCRIPTION)\n",
    "    st.download_button(\n",
    "        label=\" 📄 Download Resume\",\n",
    "        data=PDFbyte,\n",
    "        file_name=resume_file.name,\n",
    "        mime=\"application/octet-stream\",\n",
    "    )\n",
    "    st.write(\"📫\", EMAIL)\n",
    "\n",
    "\n",
    "# --- SOCIAL LINKS ---\n",
    "st.write('\\n')\n",
    "cols = st.columns(len(SOCIAL_MEDIA))\n",
    "for index, (platform, link) in enumerate(SOCIAL_MEDIA.items()):\n",
    "    cols[index].write(f\"[{platform}]({link})\")\n",
    "\n",
    "\n",
    "# --- EXPERIENCE & QUALIFICATIONS ---\n",
    "st.write('\\n')\n",
    "st.subheader(\"Experience & Qulifications\")\n",
    "st.write(\n",
    "    \"\"\"\n",
    "- ✔️ 7 Years expereince extracting actionable insights from data\n",
    "- ✔️ Strong hands on experience and knowledge in Python and Excel\n",
    "- ✔️ Good understanding of statistical principles and their respective applications\n",
    "- ✔️ Excellent team-player and displaying strong sense of initiative on tasks\n",
    "\"\"\"\n",
    ")\n",
    "\n",
    "\n",
    "# --- SKILLS ---\n",
    "st.write('\\n')\n",
    "st.subheader(\"Hard Skills\")\n",
    "st.write(\n",
    "    \"\"\"\n",
    "- 👩‍💻 Programming: Python (Scikit-learn, Pandas), SQL, VBA\n",
    "- 📊 Data Visulization: PowerBi, MS Excel, Plotly\n",
    "- 📚 Modeling: Logistic regression, linear regression, decition trees\n",
    "- 🗄️ Databases: Postgres, MongoDB, MySQL\n",
    "\"\"\"\n",
    ")\n",
    "\n",
    "\n",
    "# --- WORK HISTORY ---\n",
    "st.write('\\n')\n",
    "st.subheader(\"Work History\")\n",
    "st.write(\"---\")\n",
    "\n",
    "# --- JOB 1\n",
    "st.write(\"🚧\", \"**Senior Data Analyst | Ross Industries**\")\n",
    "st.write(\"02/2020 - Present\")\n",
    "st.write(\n",
    "    \"\"\"\n",
    "- ► Used PowerBI and SQL to redeﬁne and track KPIs surrounding marketing initiatives, and supplied recommendations to boost landing page conversion rate by 38%\n",
    "- ► Led a team of 4 analysts to brainstorm potential marketing and sales improvements, and implemented A/B tests to generate 15% more client leads\n",
    "- ► Redesigned data model through iterations that improved predictions by 12%\n",
    "\"\"\"\n",
    ")\n",
    "\n",
    "# --- JOB 2\n",
    "st.write('\\n')\n",
    "st.write(\"🚧\", \"**Data Analyst | Liberty Mutual Insurance**\")\n",
    "st.write(\"01/2018 - 02/2022\")\n",
    "st.write(\n",
    "    \"\"\"\n",
    "- ► Built data models and maps to generate meaningful insights from customer data, boosting successful sales eﬀorts by 12%\n",
    "- ► Modeled targets likely to renew, and presented analysis to leadership, which led to a YoY revenue increase of $300K\n",
    "- ► Compiled, studied, and inferred large amounts of data, modeling information to drive auto policy pricing\n",
    "\"\"\"\n",
    ")\n",
    "\n",
    "# --- JOB 3\n",
    "st.write('\\n')\n",
    "st.write(\"🚧\", \"**Data Analyst | Chegg**\")\n",
    "st.write(\"04/2015 - 01/2018\")\n",
    "st.write(\n",
    "    \"\"\"\n",
    "- ► Devised KPIs using SQL across company website in collaboration with cross-functional teams to achieve a 120% jump in organic traﬃc\n",
    "- ► Analyzed, documented, and reported user survey results to improve customer communication processes by 18%\n",
    "- ► Collaborated with analyst team to oversee end-to-end process surrounding customers' return data\n",
    "\"\"\"\n",
    ")\n",
    "\n",
    "\n",
    "# --- Projects & Accomplishments ---\n",
    "st.write('\\n')\n",
    "st.subheader(\"Projects & Accomplishments\")\n",
    "st.write(\"---\")\n",
    "for project, link in PROJECTS.items():\n",
    "    st.write(f\"[{project}]({link})\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f1cb8e87",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
